// Generated by CoffeeScript 1.6.3
(function() {
  var ICON_NAMES, attachEvent, calculateMean, calculateStdDev, finishTest, icons, iconsHTML, init, initIcons, launchTest, setIcons, test;

  ICON_NAMES = ["home", "glass", "star", "male", "female", "bug"];

  icons = [];

  iconsHTML = [];

  calculateMean = function(a) {
    var e, sum, _i, _len;
    sum = 0;
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      e = a[_i];
      sum += e;
    }
    return sum / a.length;
  };

  window.calculateVariance = function(a) {
    var e, mean, temp, _i, _len;
    temp = 0;
    mean = calculateMean(a);
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      e = a[_i];
      temp += Math.pow(mean - e, 2);
    }
    return temp / a.length;
  };

  calculateStdDev = function(a) {
    return Math.sqrt(calculateVariance(a));
  };

  initIcons = function(iconClass) {
    var i, _i;
    for (i = _i = 0; _i < 6; i = ++_i) {
      icons.push(document.getElementById("test_" + i));
      iconsHTML.push("<i class=\"" + iconClass + "-" + ICON_NAMES[i] + "\"></i>");
    }
  };

  setIcons = function(iconClass, start) {
    var i, _i;
    for (i = _i = 0; _i < 6; i = ++_i) {
      icons[(i + start) % 6].innerHTML = iconsHTML[i];
    }
  };

  attachEvent = function(element) {
    if (element.addEventListener != null) {
      return element.addEventListener('click', launchTest, false);
    } else if (element.attachEvent != null) {
      return element.attachEvent('onclick', launchTest);
    }
  };

  launchTest = function() {
    document.getElementById('startTest').setAttribute('disabled', 'disabled');
    document.getElementById('results').innerHTML = '<span class="text-warning">Please wait...</span>';
    setTimeout(function() {
      return test();
    }, 100);
  };

  finishTest = function(results) {
    document.getElementById('results').innerHTML = "<b class=\"text-success\">DONE!</b> Average: <b>" + (calculateMean(results).toFixed(2)) + "ms</b> <span class=\"text-muted\">[Standard Deviation: <b>" + (calculateStdDev(results).toFixed(2)) + "ms</b>]</span>";
    document.getElementById('startTest').removeAttribute('disabled');
  };

  test = function() {
    var bodyElement, forceRendering, i, iconClass, l, loops, results, start, stop, _i, _j;
    loops = document.getElementById('loops').value;
    results = [];
    bodyElement = document.getElementById('body');
    iconClass = bodyElement.getAttribute('data-icon-class');
    initIcons(iconClass);
    for (l = _i = 0; 0 <= loops ? _i < loops : _i > loops; l = 0 <= loops ? ++_i : --_i) {
      start = new Date().getTime();
      for (i = _j = 0; _j < 100; i = ++_j) {
        setIcons(iconClass, i % 6);
        forceRendering = bodyElement.offsetWidth + bodyElement.offsetHeight;
      }
      stop = new Date().getTime();
      results.push(stop - start);
    }
    finishTest(results);
  };

  init = function() {
    return attachEvent(document.getElementById('startTest'));
  };

  if (window.addEventListener != null) {
    window.addEventListener('load', init, false);
  } else if (window.attachEvent != null) {
    window.attachEvent('onload', init);
  } else {
    document.addEventListener('load', init, false);
  }

}).call(this);
